// Password hashing (SRS FR-AUTH-03…06, FR-RL-08).
//
// Argon2id with a per-password random salt generated by the library, an
// optional server-side pepper applied first, and a concurrency gate — hashing
// is deliberately expensive, which makes it a CPU-exhaustion vector if an
// attacker can start unlimited hashes at once.

const crypto = require('crypto');
const argon2 = require('@node-rs/argon2');
const { AppError } = require('../../shared/errors');

/**
 * Bounded-concurrency gate. Requests beyond the limit wait briefly; if the
 * queue does not clear they are told to retry rather than piling up until the
 * event loop starves.
 */
class Semaphore {
    constructor(limit, maxWaitMs = 2000) {
        this.limit = limit;
        this.maxWaitMs = maxWaitMs;
        this.active = 0;
        this.queue = [];
    }

    acquire() {
        if (this.active < this.limit) {
            this.active += 1;
            return Promise.resolve();
        }
        return new Promise((resolve, reject) => {
            const entry = { resolve, reject };
            entry.timer = setTimeout(() => {
                this.queue = this.queue.filter((q) => q !== entry);
                reject(new AppError('SERVICE_UNAVAILABLE', {
                    headers: { 'Retry-After': '2' },
                    logMessage: 'password hashing queue full',
                }));
            }, this.maxWaitMs);
            this.queue.push(entry);
        });
    }

    release() {
        const next = this.queue.shift();
        if (next) {
            clearTimeout(next.timer);
            next.resolve();
            return;
        }
        this.active = Math.max(0, this.active - 1);
    }

    async run(fn) {
        await this.acquire();
        try { return await fn(); } finally { this.release(); }
    }
}

function createPasswordService(cfg) {
    const options = {
        algorithm: argon2.Algorithm.Argon2id,
        memoryCost: cfg.ARGON2_MEMORY_KIB,
        timeCost: cfg.ARGON2_TIME_COST,
        parallelism: cfg.ARGON2_PARALLELISM,
    };
    const gate = new Semaphore(cfg.ARGON2_MAX_CONCURRENCY);
    const pepper = Buffer.from(cfg.PASSWORD_PEPPER, 'base64');

    // The pepper lives outside the database, so a stolen table alone does not
    // let an attacker start guessing. HMAC first also normalises input length.
    const peppered = (password) =>
        crypto.createHmac('sha256', pepper).update(password, 'utf8').digest('base64');

    // A hash of a random value, used to spend the same CPU when an email is
    // unknown as when it exists — otherwise response time reveals which.
    let dummyHash = null;
    const ready = (async () => {
        dummyHash = await argon2.hash(peppered(crypto.randomBytes(32).toString('hex')), options);
    })();

    async function hash(password) {
        return gate.run(() => argon2.hash(peppered(password), options));
    }

    async function verify(storedHash, password) {
        return gate.run(async () => {
            try {
                return await argon2.verify(storedHash, peppered(password), options);
            } catch {
                // a malformed or unsupported stored hash is a failed login, not a crash
                return false;
            }
        });
    }

    /** Burns comparable CPU on the unknown-user path. */
    async function verifyDummy(password) {
        await ready;
        return verify(dummyHash, password);
    }

    /** True when a stored hash was made with weaker parameters than we now use. */
    function needsRehash(storedHash) {
        const match = /^\$argon2(id|i|d)\$v=(\d+)\$m=(\d+),t=(\d+),p=(\d+)\$/.exec(storedHash || '');
        if (!match) return true;
        const [, variant, , memory, time, parallelism] = match;
        return variant !== 'id'
            || Number(memory) < options.memoryCost
            || Number(time) < options.timeCost
            || Number(parallelism) < options.parallelism;
    }

    return { hash, verify, verifyDummy, needsRehash, ready, options };
}

module.exports = { createPasswordService, Semaphore };
